/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.mmlg.ui.internal.MmlgActivator;

public class MmlgUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MmlgActivator.getInstance().getInjector("org.xtext.example.mydsl.Mmlg");
	}

}
