/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link MmlgWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractMmlgWebModule extends DefaultWebModule {

}
