/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.mmlg.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.mmlg.MmlgPackage;
import org.xtext.example.mydsl.mmlg.XFormula;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>XFormula</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class XFormulaImpl extends MinimalEObjectImpl.Container implements XFormula
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected XFormulaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MmlgPackage.Literals.XFORMULA;
  }

} //XFormulaImpl
