/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MmlgStandaloneSetup extends MmlgStandaloneSetupGenerated {

	public static void doSetup() {
		new MmlgStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
