/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.mmlg;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>All Variables</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.mmlg.AllVariables#getAll <em>All</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.mmlg.MmlgPackage#getAllVariables()
 * @model
 * @generated
 */
public interface AllVariables extends XFormula
{
  /**
   * Returns the value of the '<em><b>All</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>All</em>' attribute.
   * @see #setAll(String)
   * @see org.xtext.example.mydsl.mmlg.MmlgPackage#getAllVariables_All()
   * @model
   * @generated
   */
  String getAll();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.mmlg.AllVariables#getAll <em>All</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>All</em>' attribute.
   * @see #getAll()
   * @generated
   */
  void setAll(String value);

} // AllVariables
