/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.mmlg;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cross Validation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.mmlg.MmlgPackage#getCrossValidation()
 * @model
 * @generated
 */
public interface CrossValidation extends StratificationMethod
{
} // CrossValidation
