/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.mmlg;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>ML Algorithm</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.mmlg.MmlgPackage#getMLAlgorithm()
 * @model
 * @generated
 */
public interface MLAlgorithm extends EObject
{
} // MLAlgorithm
