/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.mmlg;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Predictor Variables</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.mmlg.PredictorVariables#getVars <em>Vars</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.mmlg.MmlgPackage#getPredictorVariables()
 * @model
 * @generated
 */
public interface PredictorVariables extends XFormula
{
  /**
   * Returns the value of the '<em><b>Vars</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.mmlg.FormulaItem}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vars</em>' containment reference list.
   * @see org.xtext.example.mydsl.mmlg.MmlgPackage#getPredictorVariables_Vars()
   * @model containment="true"
   * @generated
   */
  EList<FormulaItem> getVars();

} // PredictorVariables
